version: '3'

services:
  db: 
    image: postgres
    container_name: auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PERSISTENCE}
    ports:
      - "5434:5432"

  django:
    build: ./api
    container_name: authentication_django
    command: ash docker-entrypoint.sh
    volumes:
      - ./api:/api
    environment:
      HOST_SERVER: ${HOST_SERVER}
    ports:
      - "8090:8090"
    depends_on:
      - db
