version: '3'

networks:
  frontend_frontend_net:
    external: true
  profile_profile_net:
    external: true

services:
  db: 
    image: postgres
    container_name: auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PERSISTENCE}
    networks:
      - profile_profile_net 
    ports:
      - "5434:5432"

  django:
    build: ./api
    container_name: authentication
    command: ash docker-entrypoint.sh
    volumes:
      - ./api:/api
    environment:
      HOST_SERVER: ${HOST_SERVER}
    ports:
      - "8090:8090"
    networks:
      - profile_profile_net 
      - frontend_frontend_net 
    depends_on:
      - db
